
Aequation\WireBundle\Service\AppWireService:
    attributes:
        sessionID:
            groups: ['identifier','for_session']
        user:
            type: object
            maxDepth: 1
            groups: ['identifier','for_session']
        environment:
            type: string
            groups: ['for_session']
        firewallname:
            type: string
            groups: ['for_session']
        clientIp:
            type: string
            groups: ['for_session']
        clientIps:
            type: array
            groups: ['for_session']
        XmlHttpRequest:
            type: boolean
            groups: ['for_session']
        TurboFrameRequest:
            type: boolean
            groups: ['for_session']
        TurboStreamRequest:
            type: boolean
            groups: ['for_session']
        public:
            type: boolean
            groups: ['for_session']
        private:
            type: boolean
            groups: ['for_session']
        currentdatetime:
            type: string
            groups: ['for_session']
        debug:
            type: boolean
            groups: ['for_session']
        locale:
            type: string
            groups: ['for_session']
        enabled_locales:
            type: array
            groups: ['for_session']
        current_route:
            type: string
            groups: ['for_session']
        current_route_parameters:
            type: array
            groups: ['for_session']
        stopwatch:
            groups: ['for_session']
            getter: getStopwatchTime
        Context:
            type: array
            groups: ['for_session']
            getter: getContextAsArray
        Headers:
            type: array
            groups: ['for_session']
        charset:
            type: string
            groups: ['for_session']
        darkmode:
            type: boolean
            groups: ['for_session']
        timezone:
            type: string
            groups: ['for_session']
        datenow:
            type: string
            groups: ['for_session']
        tinyvalues:
            type: array
            groups: ['for_session']
