[
    {
        enabled: false, // DISABLED!!!
        file: 'kernel.getProjectDir() ~ "/config/packages/test.yaml"',
        create_file: true,
        insertions: [
            {
                location: 'test/firewalls',
                replace: true,
                # after_index: 'dev',
                before_index: 'main',
                data: {
                    admin: {
                        lazy: true,
                        pattern: ^/(account|s?admin|ae-),
                        provider: app_user_provider,
                    }
                },
            },
        ],
    },
    {
        file: 'kernel.getProjectDir() ~ "/config/packages/framework.yaml"',
        create_file: true,
        insertions: [
            {
                location: 'framework/default_locale',
                replace: false,
                data: '%locale%',
            },
            {
                location: 'framework/translator/fallbacks',
                replace: false,
                data: ['%locale%'],
            },
            {
                location: 'framework/translator/default_path',
                replace: false,
                data: '%kernel.project_dir%/translations',
            },
            {
                location: 'framework/translator/paths',
                replace: true,
                type: 'merge',
                data: [
                    # '%kernel.project_dir%/translations',
                    '%kernel.project_dir%/vendor/aequation/wire/translations',
                ],
            },
        ],
    },
    {
        file: 'kernel.getProjectDir() ~ "/config/packages/security.yaml"',
        create_file: false,
        insertions: [
            {
                location: 'security/providers',
                replace: false,
                data: {
                    app_user_provider: {
                        entity: {
                            class: App\Entity\User,
                            property: email,
                        },
                    },
                },
            },
            {
                location: 'security/firewalls',
                replace: true,
                # after_index: 'dev',
                before_index: 'main',
                data: {
                    admin: {
                        lazy: true,
                        pattern: ^/(account|s?admin|ae-),
                        provider: app_user_provider,
                    }
                },
            },
        ],
    },
    {
        file: 'kernel.getProjectDir() ~ "/config/packages/doctrine.yaml"',
        create_file: true,
        insertions: [
            {
                location: 'doctrine/orm/mappings',
                replace: true,
                data: {
                    AequationWireBundle: {
                        type: attribute,
                        is_bundle: true,
                        dir: '/src/Entity',
                        prefix: 'Aequation\WireBundle\Entity',
                        alias: AequationWireBundle,
                    },
                },
            },
        ],
    },
    {
        file: 'kernel.getProjectDir() ~ "/config/packages/twig.yaml"',
        create_file: true,
        insertions: [
            {
                location: 'twig/file_name_pattern',
                replace: false,
                data: '*.twig',
            },
            {
                location: 'twig/default_path',
                replace: false,
                data: '%kernel.project_dir%/templates',
            },
            # {
            #     location: 'twig/paths',
            #     replace: true,
            #     type: 'merge',
            #     data: {
            #         '%kernel.project_dir%/vendor/aequation/wire/templates/bundles/EasyAdminBundle': 'EasyAdmin',
            #     },
            # },
            {
                location: 'twig/form_themes',
                replace: true,
                type: 'merge',
                data: ['@AequationWire/form/wire_app_layout.html.twig'],
            },
            {
                location: 'twig/globals',
                replace: true,
                type: 'merge',
                data: {
                    app: '@Aequation\WireBundle\Service\interface\AppWireServiceInterface'
                },
            },
        ],
    },
    {
        file: 'kernel.getProjectDir() ~ "/config/packages/notifier.yaml"',
        create_file: true,
        insertions: [
            {
                location: 'framework/notifier',
                replace: false,
                data: {
                    admin_recipients: [
                        { email: '%main_sadmin%' },
                    ],
                },
            },
        ],
    },
    {
        file: 'kernel.getProjectDir() ~ "/config/services.yaml"',
        create_file: true,
        insertions: [
            {
                location: 'parameters',
                replace: true,
                type: 'add',
                data: {
                    ae_wire_installed: true,
                    main_sadmin: manu7772@gmail.com,
                    main_admin: sebastien.polin123@orange.fr,
                    on_create_roles: {
                        '%main_admin%': ROLE_ADMIN,
                        '%main_sadmin%': ROLE_SUPER_ADMIN,
                    },
                    mail_from: {
                        '%main_admin%': 'Sébastien Polin',
                    },
                    mail_to_admin: {
                        '%main_admin%': 'Sébastien Polin',
                    },
                    mail_to_dev: {
                        '%main_sadmin%': 'Emmanuel Dujardin',
                        # 'emmanuel@aequation.fr': 'Dujardin Aequation',
                        # 'manu7772@protonmail.com': 'Manu Protonmail',
                    },
                    vich_dirs.item_photo: '/uploads/images/item',
                    vich_dirs.user_portrait: '/uploads/images/user',
                    vich_dirs.slider_slides: '/uploads/images/slides',
                    vich_dirs.pdf: '/uploads/pdf',
                    locale: '%env(APP_LOCALE)%',
                    # locales: ['%env(APP_LOCALE)%']
                    currency: '%env(APP_CURRENCY)%',
                    timezone: '%env(APP_TIMEZONE)%',
                    darkmode: true,
                    clean_directorys: [
                        'public/uploads',
                        'public/media',
                    ],
                    custom_colors: ['primary','secondary','info','success','warning','danger','error'],
                    notif: {
                        app: 'notyf',
                        types: '%custom_colors%',
                        router.request_context.host: vetoalliance.com,
                        router.request_context.scheme: 'https',
                        asset.request_context.secure: true,
                    },
                },
            },
            {
                location: 'services/App\/exclude',
                replace: true,
                # type: 'merge',
                data: [
                    '../src/DependencyInjection/',
                    '../src/Component/',
                    '../src/Entity/',
                    '../src/Kernel.php',
                ],
            },
        ],
    },
]